### ISSUE TITLE
Declaração do evento de inclusão de condutor está funcional?

### ISSUE THREAD

**Issue by Emerson-Gabriel** [nfephp-org/sped-averbacao#23]
Ao realizar testes no processo de declaração do evento de inclusão de condutor de um MDF-e estou recendo alguns retornos como:
`<?xml version="1.0" encoding="utf-8"?>
<SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/">
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <faultcode xsi:type="xsd:string">SOAP-ENV:Client</faultcode>
      <faultactor xsi:type="xsd:string"></faultactor>
      <faultstring xsi:type="xsd:string">error in msg parsing:
XML error parsing SOAP payload on line 4: Undeclared entity error</faultstring>
      <detail xsi:type="xsd:string"></detail>
    </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

Alguém pode me informar se o componente esta correto?

**Comment by robmachado** [comment]
O que inclusão de condutor do MDFe tem haver com AVERBAÇÃO de SEGURO ????

**Comment by Emerson-Gabriel** [comment]
> O que inclusão de condutor do MDFe tem haver com AVERBAÇÃO de SEGURO ????

Boa tarde, como visto no manual da ATM existe uma rota para realizar a declaração do Evento de Inclusão de Condutor veja:
![Inc cond](https://github.com/nfephp-org/sped-averbacao/assets/18463395/efb54a78-97e4-4717-a9ec-9a9edf589596)

Ou seja todo MDF-e que for feita a inclusão de condutor após a declaração do MDF-e para a seguradora, deverá ter a inclusão do condutor declarada também.

**Comment by robmachado** [comment]
OK Meu colega, mas no sped-averbação não é feito nada disso este pacote não tem nada haver com o problema do sped-mdfe !

**Comment by robmachado** [comment]
A que eu saiba ! a ATM averba NFe e/ou CTe é gera o numero necessário para declarar na MDFe o manual que eu tenho é esse http://s3box.atmtec.com.br/Manual_AT&M_Integracao_WebService_v30_1.pdf
